# Generated by Django 3.0.7 on 2020-06-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_lists", "0004_remove_todo_created_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="todolist", name="created_at",),
    ]
