# Generated by Django 3.0.7 on 2020-07-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_lists", "0005_remove_todolist_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo", name="is_done", field=models.BooleanField(default=False),
        ),
    ]
