# Generated by Django 3.0.4 on 2020-05-21 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todo_list", "0002_auto_20200521_0301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_lists",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
