# Generated by Django 3.0.4 on 2020-05-18 19:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20200512_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoList',
        ),
    ]
